### ISSUE TITLE
Exec format error on arm64 devices

### ISSUE THREAD

**Issue by Happyfeet01** [janis91/ocr#123]
Hello,

Is it possible to make an version for arm64 and aarch64 devices?

When I run this command:

```
docker build --build-arg LANGUAGES="tesseract-ocr-deu" -t www-data/ocr .
```
I got an exec format error.

```
root@odroid64:/var/www/nextcloud/apps/ocr/worker# docker build --build-arg LANGUAGES="tesseract-ocr-deu" -t www-data/ocr .
Sending build context to Docker daemon 57.34 kB
Step 1 : FROM ubuntu:16.10
16.10: Pulling from library/ubuntu
dca7be20e546: Pull complete
40bca54f5968: Pull complete
61464f23390e: Pull complete
d99f0bcd5dc8: Pull complete
120db6f90955: Pull complete
Digest: sha256:8dc9652808dc091400d7d5983949043a9f9c7132b15c14814275d25f94bca18a
Status: Downloaded newer image for ubuntu:16.10
 ---> 7d3f705d307c
Step 2 : LABEL maintainer "janiskoehr@icloud.com" description "This image serves the dependencies like tesseract and OCRmyPDF and the ocr worker for the nextcloud ocr app." vendor "Janis Koehr"
 ---> Running in ccaf911eca53
 ---> 8feb6e183a58
Removing intermediate container ccaf911eca53
Step 3 : ARG LANGUAGES="tesseract-ocr-fra tesseract-ocr-spa tesseract-ocr-deu"
 ---> Running in ca57d9b92401
 ---> 3ac2d08f5aef
Removing intermediate container ca57d9b92401
Step 4 : RUN groupadd --gid 1000 node     && useradd --uid 1000 --gid node --shell /bin/bash --create-home node
 ---> Running in 82b901687339
panic: standard_init_linux.go:178: exec user process caused "exec format error" [recovered]
        panic: standard_init_linux.go:178: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x7c6fc0, 0x48201569a0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x384
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction.func1(0x48200ff2c0)
        /build/runc-k8IjLv/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:478 +0x330
panic(0x7c6fc0, 0x48201569a0)
        /usr/lib/go-1.6/src/runtime/panic.go:443 +0x4b4
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0x48200febc0, 0x482001e0c8, 0x48200fecd0)
        /build/runc-k8IjLv/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x190
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0x482005d590, 0x7f9dfa8728, 0x48201569a0)
        /build/runc-k8IjLv/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x4d8
main.glob.func8(0x482007ea00, 0x0, 0x0)
        /build/runc-k8IjLv/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/main_unix.go:26 +0x50
reflect.Value.call(0x72c7a0, 0x8dbd20, 0x13, 0x8230a8, 0x4, 0x48200ff240, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/lib/go-1.6/src/reflect/value.go:435 +0xeec
reflect.Value.Call(0x72c7a0, 0x8dbd20, 0x13, 0x48200ff240, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/reflect/value.go:303 +0x88
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction(0x72c7a0, 0x8dbd20, 0x482007ea00, 0x0, 0x0)
        /build/runc-k8IjLv/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:487 +0x23c
github.com/opencontainers/runc/vendor/github.com/urfave/cli.Command.Run(0x825e78, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8bb160, 0x51, 0x0, ...)
        /build/runc-k8IjLv/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:191 +0xdc8
github.com/opencontainers/runc/vendor/github.com/urfave/cli.(*App).Run(0x4820001b00, 0x482000a100, 0x2, 0x2, 0x0, 0x0)
        /build/runc-k8IjLv/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:240 +0x8e4
main.main()
        /build/runc-k8IjLv/runc-1.0.0~rc2+docker1.12.6/_build/src/github.com/opencontainers/runc/main.go:137 +0xce4
The command '/bin/sh -c groupadd --gid 1000 node     && useradd --uid 1000 --gid node --shell /bin/bash --create-home node' returned a non-zero code: 2
```

I don't know if you can do anything?

**Comment by janis91** [comment]
I will look into this as soon as possible. Actually I expected it to work on arm because it uses docker. But maybe there are some things, that don't behave like expected.

**Comment by janis91** [comment]
OK, I now know, that there is a difference between armhf containers and non-armhf containers for docker. So I will work on an armhf version of the ocr worker asap.

**Comment by janis91** [comment]
This seems more difficult than I expected. I put this on hold and try again at a later date.

**Comment by janis91** [comment]
One proposal that i can make currently is:
install everything by hand and do not use docker. Should be even less overhead and therefore better performance wise. You can follow the dockerfile a bit for this.
