### ISSUE TITLE
RuntimeError: ocrmypdf will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.

### ISSUE THREAD

**Issue by mathiasconradt** [janis91/ocr#126]
I setup the OCR app using the docker approach as per documentation.

OCR processing of images is working fine, but processing PDFs via ocrmypdf fails with this error message in the OCR docker container:

```
RuntimeError: ocrmypdf will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.

2017-11-23T10:54:18.183Z - error: Job errored: The execution of 'ocrmypdf' command failed: Traceback (most recent call last):
  File "/usr/local/bin/ocrmypdf", line 7, in <module>
    from ocrmypdf.__main__ import run_pipeline
  File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/__main__.py", line 53, in <module>
    _unicodefun._verify_python3_env()
  File "/usr/local/lib/python3.5/dist-packages/ocrmypdf/_unicodefun.py", line 108, in _verify_python3_env
    'environment.' + extra)
RuntimeError: ocrmypdf will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.
2017-11-23T10:54:18.183622441Z 
This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:
2017-11-23T10:54:18.183651607Z 
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
```

I already tried to set 

```
    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8
```

in the OCR docker container, but it does not seem to help.

What's weird though: when I run `ocrmypdf test.pdf test_out.pdf` in the command line of the docker container (instead of trigger it from the Nextcloud webclient), I don't get this error and the processing succeeds. 

I assume this has something to do with the OCR docker image configuration.

When I bash into the docker container and run this python test script,

```
import os
print(os.environ.get('LC_ALL'))
print(os.environ.get('LANG'))
```

I also get correctly

```
node@8c1622e7bfa9:~/output$ python3 test.py
C.UTF-8
C.UTF-8
```

I don't get why the it doesn't pick up the right encoding settings when run from via Nextcloud webclient as opposed to running ocrmypdf directly.

**Comment by mathiasconradt** [comment]
While updating the environment variables via bash in the Docker container does not work, adding these two lines to the `worker/Dockerfile` seems to solve the problem.

```
ENV LC_ALL="C.UTF-8"
ENV LANG="C.UTF-8"
```
