### ISSUE TITLE
Breaks Nextcloud 11

### ISSUE THREAD

**Issue by oparoz** [janis91/ocr#59]
# Bug report
## Expected Behavior

I should be able to keep using NExtcloud even if the app is broken.

## Current Behavior

It's impossible to use the Files app

## Steps to Reproduce (for bugs)

1. Enable app

## Context

Add exception handling to not break Nextcloud when a serious issue occurs.

## Your Environment

* OCR version used:

```
tesseract 3.04.01
 leptonica-1.72
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.1) : libpng 1.6.28+apng : libtiff 4.0.7 : zlib 1.2.8 : libwebp 0.5.2 : libopenjp2 2.1.2
```

* ownCloud/nextcloud version: 11.0.1
* PHP version: 7.1
* Database version
* Are you using encryption: no

## Log File Content (nextcloud/owncloud.log of the "data"-directory)

```
An unhandled exception has been thrown:
Error: Call to undefined function OCA\Ocr\Service\msg_get_queue() in customapps/ocr/lib/Service/QueueService.php:70
Stack trace:
#0 [internal function]: OCA\Ocr\Service\QueueService->__construct(Object(OCA\Ocr\Db\OcrStatusMapper), Object(OC\AllConfig), Object(OC\L10N\L10N), Object(OC\Log))
#1 lib/private/AppFramework/Utility/SimpleContainer.php(79): ReflectionClass->newInstanceArgs(Array)
#2 An unhandled exception has been thrown:
Error: Call to undefined function OCA\Ocr\Service\msg_get_queue() in customapps/ocr/lib/Service/QueueService.php:70
Stack trace:
#0 [internal function]: OCA\Ocr\Service\QueueService->__construct(Object(OCA\Ocr\Db\OcrStatusMapper), Object(OC\AllConfig), Object(OC\L10N\L10N), Object(OC\Log))
#1 lib/private/AppFramework/Utility/SimpleContainer.php(79): ReflectionClass->newInstanceArgs(Array)
#2 lib/private/AppFramework/Utility/SimpleContainer.php(96): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#3 lib/private/AppFramework/Utility/SimpleContainer.php(117): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Ocr\\Service...')
#4 lib/private/AppFramework/DependencyInjection/DIContainer.php(544): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Ocr\\Service...')
#5 lib/private/AppFramework/Utility/SimpleContainer.php(66): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Ocr\\Service...')
#6 lib/private/AppFramework/Utility/SimpleContainer.php(96): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#7 lib/private/AppFramework/Utility/SimpleContainer.php(117): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Ocr\\Service...')
#8 lib/private/AppFramework/DependencyInjection/DIContainer.php(544): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Ocr\\Service...')
#9 lib/private/AppFramework/Utility/SimpleContainer.php(66): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Ocr\\Service...')
#10 lib/private/AppFramework/Utility/SimpleContainer.php(96): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#11 lib/private/AppFramework/Utility/SimpleContainer.php(117): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Ocr\\Command...')
#12 lib/private/AppFramework/DependencyInjection/DIContainer.php(544): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Ocr\\Command...')
#13 customapps/ocr/appinfo/register_command.php(18): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Ocr\\Command...')
#14 lib/private/Console/Application.php(119): require('/backyard/yourmum/d...')
#15 console.php(89): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 occ(11): require_once('/backyard/yourmum/d...')
#17 {main}/lib/private/AppFramework/Utility/SimpleContainer.php(96): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#3 lib/private/AppFramework/Utility/SimpleContainer.php(117): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Ocr\\Service...')
#4 lib/private/AppFramework/DependencyInjection/DIContainer.php(544): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Ocr\\Service...')
#5 lib/private/AppFramework/Utility/SimpleContainer.php(66): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Ocr\\Service...')
#6 lib/private/AppFramework/Utility/SimpleContainer.php(96): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#7 lib/private/AppFramework/Utility/SimpleContainer.php(117): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Ocr\\Service...')
#8 lib/private/AppFramework/DependencyInjection/DIContainer.php(544): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Ocr\\Service...')
#9 lib/private/AppFramework/Utility/SimpleContainer.php(66): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Ocr\\Service...')
#10 lib/private/AppFramework/Utility/SimpleContainer.php(96): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#11 lib/private/AppFramework/Utility/SimpleContainer.php(117): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Ocr\\Command...')
#12 lib/private/AppFramework/DependencyInjection/DIContainer.php(544): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Ocr\\Command...')
#13 customapps/ocr/appinfo/register_command.php(18): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Ocr\\Command...')
#14 lib/private/Console/Application.php(119): require('/backyard/yourmum/d...')
#15 console.php(89): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 occ(11): require_once('/backyard/yourmum/d...')
#17 {main}
```

**Comment by janis91** [comment]
I have an idea, what this is about:  maybe the message queuing feature of php isn't available in your php version. Could you check that?

If this is the case, I actually don't know how to check if a php feature is available, in order to handle this.

**Comment by oparoz** [comment]
Yep, maybe add this requirement to the app description?
Also, it would be great to switch to Redis which is more likely to be enabled given all the advantages it brings.

To check, simply use a try-catch with a function call and generate a log entry to let the admin know.

**Comment by janis91** [comment]
Hi, for now I won't switch to Redis, as I think it's somehow overkill and the semaphore functions of php will stay in place for the standard php7 installation package of debian and ubuntu, as far as I see.
Maybe this will change in the future, but at the moment I think this is better.

**Comment by janis91** [comment]
https://github.com/janis91/ocr/wiki/OCR-app-installation---enabling-fails
