### ISSUE TITLE
OCR App could not be initialized: "No languages found."

### ISSUE THREAD

**Issue by oparoz** [janis91/ocr#61]
Warning at the top says:
OCR App could not be initialized: "No languages found."

but I do have languages installed

```
# tesseract --list-langs
List of available languages (4):
deu
equ
osd
eng
```

## Your Environment

* OCR version used: 2.3.0
* ownCloud/nextcloud version: 11.0.1
* PHP version: 7.1.1

## Log File Content (nextcloud/owncloud.log of the "data"-directory)

```
"message": "Exception during ocr service function processing: {\"Exception\":\"OCA\\\\Ocr\\\\Service\\\\NotFoundException\",\"Message\":\"No languages found.\",\"Code\":0,\"Trace\":\"#0 \\\/customapps\\\/ocr\\\/lib\\\/Controller\\\/OcrController.php(61): OCA\\\\Ocr\\\\Service\\\\OcrService->listLanguages()\\n#1 \\\/customapps\\\/ocr\\\/lib\\\/Controller\\\/Errors.php(35): OCA\\\\Ocr\\\\Controller\\\\OcrController->OCA\\\\Ocr\\\\Controller\\\\{closure}()\\n#2 \\\/customapps\\\/ocr\\\/lib\\\/Controller\\\/OcrController.php(62): OCA\\\\Ocr\\\\Controller\\\\OcrController->handleNotFound(Object(Closure))\\n#3 [internal function]: OCA\\\\Ocr\\\\Controller\\\\OcrController->languages()\\n#4 \\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#5 \\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Ocr\\\\Controller\\\\OcrController), 'languages')\\n#6 \\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Ocr\\\\Controller\\\\OcrController), 'languages')\\n#7 \\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OcrController', 'languages', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/ocr')\\n#11 \\\/index.php(40): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/customapps\\\/ocr\\\/lib\\\/Service\\\/OcrService.php\",\"Line\":142}"
```

**Comment by oparoz** [comment]
### Suggestion

Add a debug point before the test at:
https://github.com/janis91/ocr/blob/master/lib/Service/OcrService.php#L126

**Comment by janis91** [comment]
Don't get this wrong, but currently i am very busy. I plan to update the app as soon as possible, but ai don't know when this will be. Maybe in two weeks or so.. but i will definitely work this out ;-)

**Comment by oparoz** [comment]
Note a problem :). I'm just testing and reporting issues as I find them :)

**Comment by janis91** [comment]
The debug point has been added. If you are still recieving this error, please open a new issue. Closed for now.
